image:
  file: .gitpod/Dockerfile
tasks:
  - name: Setup KubeConfig
    command: mkdir -p ~/.kube && curl https://gist.githubusercontent.com/katcosgrove/605d78a608adebc6bcb984769c0e649f/raw/742cf9cc28d9826e27aee40a14385ddc44db3649/.kubeconfig -o ~/.kube/config
  - name: Start Docker Daemon
    command: sudo docker-up &
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Pulumi
    command: pulumi login
ports:
  - port: 5000
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - kevinrose.vsc-python-indent@1.12.0:NOHaOm1IToFrG4fit4+hUw==
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - robole.marky-markdown@2.7.0:2U+QLvBKB2yBSqNexOeyJg==
